export const MEMORY_GAME_CARD_ACTION = 'MEMORY_GAME@CARD_ACTION'
export const MEMORY_GAME_CLEAR = 'MEMORY_GAME@CLEAR'
export const MEMORY_GAME_FETCH_CARD = 'MEMORY_GAME@FETCH_CARD'
export const MEMORY_GAME_SET_GAME_CARDS = 'MEMORY_GAME@SET_GAME_CARDS'
export const MEMORY_GAME_START_GAME = 'MEMORY_GAME@START_GAME'
export const MEMORY_GAME_TOGGLE_DEMONSTRATION =
  'MEMORY_GAME@TOGGLE_DEMONSTRATION'
