export const MEMORY_GAME_ADD_MOVEMENT = 'MEMORY_GAME@ADD_MOVEMENT';
export const MEMORY_GAME_CARD_ACTION = 'MEMORY_GAME@CARD_ACTION';
export const MEMORY_GAME_CLEAR = 'MEMORY_GAME@CLEAR';
export const MEMORY_GAME_SET_GAME_CARDS = 'MEMORY_GAME@SET_GAME_CARDS';
export const MEMORY_GAME_START_GAME = 'MEMORY_GAME@START_GAME';
